volumes:
  maria_db:

networks:
  frontend:
  backend:

services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: nick
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - maria_db:/var/lib/mysql
    networks:
      - backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 8002:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - frontend
      - backend
  php:
    build: './php/'
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - ./apache/app/:/var/www/html/
  web:
    build: './apache/'
    depends_on:
      - php
      - db
    ports:
      - "80:80"
    networks:
      - frontend
      - backend
    volumes:
      - ./apache/app/:/var/www/html/